### ISSUE TITLE
Clicking a placeholder inside the breadcrumb will generate an exception. 

### ISSUE THREAD

**Issue by albandiguer** [conversionfoundry/breeze#14]
Example on numat > agrimat

**Comment by isaacfreeman** [comment]
The placeholder currently generates a link to JS void(0), which I didn't test in the breadcrumb.

Really, it shouldn't be up to the placeholder model to decide what link it generates, because it may be different in different places.

I'd suggest we modify the breadcrumb helper method to recognise placeholders and insert something appropriate – perhaps a link to the placeholder's parent.

We should also update the navigation helper method to use a <span> for placeholders instead of a link. If it's not really a link, we shouldn't use link markup. This will make the CSS slightly more complicated, but I think it's a pretty common practice.

**Comment by albandiguer** [comment]
As a placeholder is not meant to be a leaf in the tree navigation, we could link to the first children which is in certain cases the landing page, or indeed remove the link on the text which is by far the best solution.
