### ISSUE TITLE
Updating custom type name in the backend does not affect the front end.

### ISSUE THREAD

**Issue by albandiguer** [conversionfoundry/breeze#19]
Renamed the component in the backend, the same name appears in the selection box in the front end.

**Comment by ShaneNZ** [comment]
Updating the custom type name on the backend also does not update the name of the partial that Breeze is looking for e.g create a custom type called foo, partial is foo.html.erb - rename the custom type to bar, partial is still foo.html.erb (shown on the right side of the admin interface, also verified via page HTML generation).

**Comment by isaacfreeman** [comment]
I suspect that this was probably a deliberate design decision at some point in Breeze's history, so that admins could rename a custom type without breaking the appearance on the front end.

It seems reasonable to change it, but perhaps there should be an "are you sure?" message if people change a custom type name in admin.

**Comment by isaacfreeman** [comment]
Pull request submitted for this issue.
